if(WIN32)
    set(PLATFORM_WINDOWS TRUE)
    message(STATUS "Platform: Windows")
elseif(UNIX AND NOT APPLE)
    set(PLATFORM_LINUX TRUE)
    message(STATUS "Platform: Linux")
elseif(APPLE)
    set(PLATFORM_MACOS TRUE)
    message(STATUS "Platform: macOS")
endif()

if(PLATFORM_WINDOWS)
    set(PLATFORM_NAME "Windows")
    set(EXECUTABLE_EXTENSION ".exe")
elseif(PLATFORM_LINUX)
    set(PLATFORM_NAME "Linux")
    set(EXECUTABLE_EXTENSION "")
elseif(PLATFORM_MACOS)
    set(PLATFORM_NAME "macOS")
    set(EXECUTABLE_EXTENSION "")
endif()

function(add_platform_sources target)
    if(PLATFORM_WINDOWS)
        target_sources(${target} PRIVATE ${ARGN})
    endif()
endfunction()

function(link_platform_libraries target)
    if(PLATFORM_WINDOWS)
        target_link_libraries(${target} PRIVATE ws2_32 wsock32)
    elseif(PLATFORM_LINUX)
        target_link_libraries(${target} PRIVATE pthread)
    endif()
endfunction()
